### ISSUE TITLE
SharpDisasm crashes on certain code (async state machine)

### ISSUE THREAD

**Issue by ashmind** [ashmind/TryRoslyn#79]
From @davidfowl (https://github.com/ashmind/TryRoslyn/issues/39#issuecomment-298152571):

```C#
using System;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;

static class C {
    static int M(int x) 
    { 
        return Foo(x + 0x12345).Result;
    }
    
    // [MethodImpl(MethodImplOptions.NoInlining)]
    static async Task<int> Foo(int x)
    {
        return x;
    }
}
```

Exception:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SharpDisasm.Udis86.Decode.decode_vex(ud& u)
   at SharpDisasm.Udis86.Decode.decode_ext(ud& u, UInt16 ptr)
   at SharpDisasm.Udis86.Decode.decode_opcode(ud& u)
   at SharpDisasm.Udis86.Decode.ud_decode(ud& u)
   at SharpDisasm.Udis86.udis86.ud_disassemble(ud& u)
   at SharpDisasm.Disassembler.NextInstruction()
   at SharpDisasm.Disassembler.<Disassemble>d__0.MoveNext()
   at TryRoslyn.Server.Decompilation.JitAsmDecompiler.DisassembleAndWrite(JitCompiledMethod method, Translator translator, TextWriter writer)
   at TryRoslyn.Server.Decompilation.JitAsmDecompiler.Decompile(Stream assemblyStream, TextWriter codeWriter)
   at TryRoslyn.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by ashmind** [comment]
Note to self: probably OK, but need to retest after #82.

**Comment by ashmind** [comment]
OK, no regression after #82.
