### ISSUE TITLE
Null ref in async method asm conversion

### ISSUE THREAD

**Issue by davidfowl** [ashmind/TryRoslyn#84]
https://tryroslyn.azurewebsites.net/#f:>asmr/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUKSWRFDAOgBUALAJ1QEMATQiukAaxB33GniTXSkASsAjIw6VKQDCAe3QAHMABtU1OGoBuYAMapOePCjridMHctYgY0mAG88MJzGOmYkZDACyACg8wADwBKGEdnO1DcZ2iYWmRgaggYADFZWR8AmABqGAAGAIBGACYAZgAWAFYg4X1gZWQuaIBfMKdWmAB6DpgAbS9UZEpZBgBJRWUffsHhsYVlAHkFcVkIEFIAOVkRiGVIQiCAXXbXXRhWBAgzclY2AB4PAD4UtL8xQKD2hyiYpziEpICjWcLVwTSAA=

It used to be an index out of range, now I see a null ref:

```C#
using System;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;

static class C {
    static int M(int x) 
    { 
        return Foo(x + 0x12345).Result;
    }
    
    // [MethodImpl(MethodImplOptions.NoInlining)]
    static async Task<int> Foo(int x)
    {
        return x;
    }
}
```

### Release (NuGet)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at TryRoslyn.Server.Decompilation.JitAsmDecompiler.DisassembleAndWrite(IntPtr methodPointer, Translator translator, TextWriter writer)
   at TryRoslyn.Server.Decompilation.JitAsmDecompiler.Decompile(Stream assemblyStream, TextWriter codeWriter)
   at TryRoslyn.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
Built by Andrey Shchekin (@ashmind). See TryRoslyn on GitHub.
```

**Comment by davidfowl** [comment]
Seems like the entire site is broke for asm generation. Not just async methods.

**Comment by ashmind** [comment]
@davidfowl Yep, I think I know what's wrong, but a bit hard to diagnose, put in a guesswork fix for now.

**Comment by ashmind** [comment]
Should work now, I think the issue is in clrmd not recognizing dynamically loaded assemblies after a few iterations, either because they all share the same name, or due to concurrency, or due to some bug.

Anyways I reduced the lifetime of clrmd session and seems to be ok, though obviously adds some perf overhead.
